baseURL = "https://joeolaoye.co/blog/"
title = "Thoughts and Words"
theme = "ananke"   # or your chosen theme
languageCode = 'en-us'
paginate = 10
[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"  # use any theme that supports Modules
[caches]
  [caches.images]
    dir = ":cacheDir/images"